apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-app-deployment
  labels:
    app: demo-voting-app
    tier: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-voting-app
      tier: frontend
      component: result
  template:
    metadata:
      labels:
        app: demo-voting-app
        tier: frontend
        name: result-app-pod
        component: result
    spec:
      containers:
      - name: result-app
        image: kodekloud/examplevotingapp_result:v1
        env:
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: POSTGRES_HOST
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: password
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: POSTGRES_DB  
        ports:
        - containerPort: 80
