apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  labels:
    app: demo-voting-app
type: Opaque
data:
  # Base64 encoded values
  # postgres -> cG9zdGdyZXM=
  # postgres -> cG9zdGdyZXM=
  username: cG9zdGdyZXM=
  password: cG9zdGdyZXM=
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-credentials
  labels:
    app: demo-voting-app
type: Opaque
data:
  # Redis typically doesn't need password in this setup, but keeping for future use
  # redis -> cmVkaXM=
  password: ""