apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: demo-voting-app
spec:
  selector:
    app: demo-voting-app
    tier: backend
    component: redis
  ports:
  - name: redis
    port: 6379
    targetPort: 6379