apiVersion: v1
kind: Service
metadata:
  name: voting-service
  labels:
    app: demo-voting-app
spec:
  type: NodePort
  selector:
    app: demo-voting-app
    tier: frontend
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30080
